// template-projects/vue-ciderjs/src/pages/detail/user.vue
<template>
  <div>
    <h2>User Show Page</h2>
    <p>User ID: {{ params.id }}</p>
  </div>
</template>

<script setup lang="ts">
import { useParams } from "@ciderjs/city-gas/vue";

const params = useParams("/detail/user");
</script>

<script lang="ts">
import {z} from 'zod';
export const schema = z.object({ id: z.string() });
</script>

// template-projects/react-ciderjs/src/pages/detail/user.tsx
import { useParams } from "@ciderjs/city-gas/react";
import { z } from "zod";

export const schema = z.object({
  id: z.string(),
});

export default function Page() {
  const { id } = useParams("/detail/user");
  return (
    <>
      <h1>
        Detail of User <code>{id}</code>
      </h1>
      <p>Enjoy your code life!</p>
    </>
  );
}
